name: "Build new docker builderimage"

on:
    push:
        paths:
            - "Dockerfile"
            - ".github/workflows/update-dockerimg.yml"

jobs:
    publish-image:
        name: "Build and publish image"
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v2
            - name: Isolate Dockerfile
              run: 'mkdir /tmp/builderimage && cp -fv Dockerfile /tmp/builderimage/Dockerfile'
            - name: Docker metadata
              id: meta
              uses: crazy-max/ghaction-docker-meta@v1
              with:
                images: foxburu/openwrt/builderimage
                tag-sha: true
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to GH PDR
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.CTOKEN }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                context: /tmp/builderimage
                file: /tmp/builderimage/Dockerfile
                platforms: linux/amd64
                tags: ${{ steps.meta.outputs.tags }}
                labels: |
                  ${{ steps.meta.outputs.labels }}
                  org.opencontainers.image.title=builderimage
                  org.opencontainers.image.description=Custom image to build openwrt on a GHA
                push: true
            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
